import Link from "next/link"
import { Github, Twitter, Heart } from "lucide-react"

export function PortfolioFooter() {
  return (
    <footer className="border-t mt-16 py-8 bg-muted/30">
      <div className="container mx-auto px-4">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <span>Generated by</span>
            <Link href="/" className="text-primary hover:underline font-medium">
              Foliox
            </Link>
            <span className="hidden md:inline">·</span>
            <span className="hidden md:inline">Powered by GitHub & Groq AI</span>
          </div>

          <div className="flex items-center gap-4">
            <a
              href="https://github.com/yourusername/foliox"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-primary transition-colors"
            >
              <Github className="h-5 w-5" />
            </a>
            <a
              href="https://twitter.com/yourusername"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-primary transition-colors"
            >
              <Twitter className="h-5 w-5" />
            </a>
          </div>
        </div>

        <div className="mt-4 text-center text-xs text-muted-foreground">
          <p className="flex items-center justify-center gap-1">
            Made with <Heart className="h-3 w-3 text-red-500 fill-red-500" /> for developers
          </p>
        </div>
      </div>
    </footer>
  )
}

